### ISSUE TITLE
separate analytics queries into tabs

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/analytics-dashboard#26]
from @RamRamez - he noticed that we load lots of heavy queries on the analytics dashboard page, this can cause timeouts and other sorts of errors since we are trying to load so much data all at once. His suggestion was to break up the data into more digestable segments, mitigating there errors. 

We should create a navbar that is fixed to the top of the page. The navbar contains tabs that can be toggled and changes which queries are shown on the page. We should have these tabs:

- Donations 
- Recurring Donations 
- Projects
- Multisig
- Optional Donation Box

Inside of each tab we place the corresponding query inputs, outputs & graphs

### Donations 
- Donors Count
- Donations Count
- Total Donations USD Value
- New Donors Count
- New Donors Total Donation Value USD

### Recurring Donations
- Recurring Donations Count 
- Recurring Donations Total USD Value

### Projects 
- Projects Count

### Multisig 
- Multisig Sessions Count

### Optional Donation Box 
- Donation Box Metrics

The design is not important on this issue as it is a back-office tool we use for stats gathering but I envision the tabs to look something like this: 

![Image](https://github.com/user-attachments/assets/a08e4710-958c-480f-bb48-8a2b6bbf1701)

**Comment by ae2079** [comment]
@divine-comedian 
I merged the PR and now, you can test this feature on the staging (https://staging.stats.giveth.io/)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi could you please test this issue out? 

1. Check the organization of the queries into the tabs match the specifications above.
2. Check that all queries in all tabs still function as expected

There is a known issue where sometimes "failed to fetch" still occurs but after you navigate to a few different tabs the data will eventually load correctly.

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @ae2079 



The Analytics board has now been updated as per the new requirement.

The Nav Bar containing the required Tabs

Donations: Pass
Recurring Donations: Pass
Projects: Pass
Multisig: Pass
Optional Donation Box: Pass

![image](https://github.com/user-attachments/assets/ee5a110d-2b92-40e2-8b84-9c9e6c49b632)



Inside of each tab are replaced the corresponding query inputs, outputs & graphs

**Donations**
Donors Count : Pass
Donations Count: Pass
Total Donations USD Value: Pass
New Donors Count: Pass
New Donors Total Donation Value USD: Pass
Recurring Donations: Pass
Recurring Donations Count: Pass
Recurring Donations Total USD Value: Pass


**Projects**
Projects Count: Pass


**Multisig**

Multisig Sessions Count: Pass


**Optional Donation Box**
Donation Box Metrics: Pass

**Donations**
New Donors Count : **Pass**
New Donors Donations Total in USD: **Pass**



**Donations with Gnosis Chain**
Donors Count : **Pass**
Donations Count: **Pass**
Total Donations USD Value: **Pass**



**Donations with Optimism Sepolia**
Donors Count : **Pass**
Donations Count: **Pass**
Total Donations USD Value: **Pass**



**Donations with Polygon**
Donors Count : **Pass**
Donations Count: **Pass**
Total Donations USD Value: **Pass**



**Donations with Polygon zkevm**
Donors Count : **Pass**
Donations Count: **Pass**
Total Donations USD Value: **Pass**


**Donations with Arbitrum Sepolia**
Donors Count : **Pass**
Donations Count: **Pass**
Total Donations USD Value: **Pass**



**Donations with Celo Alfojores**
Donors Count : **Pass**
Donations Count: **Pass**
Total Donations USD Value: **Pass**


**Donations with Base Sepolia**
Donors Count : **Pass**
Donations Count: **Pass**
Total Donations USD Value: **Pass**



**Donations with Solan Devnet**
Donors Count : **Pass**
Donations Count: **Pass**
Total Donations USD Value: The amount here doubles



**Donations Using the Optional Donation box**

Total Donations to Giveth Using the Donation Box: **Pass**
Total USD Value to Giveth Donation using Box: **Pass**
Average Percentage Donation to Giveth Using Donation Box: **Pass**



**Recurring Donations**

Recurring Donations Count: **Pass**
Total Recurring Donations in USD:  This does not reflect immediately, will confirm by tomorrow


**Multisig**

Multisig Sessions Count: **After connecting a Safe wallet with different signers on different browsers, no count was registered on the Analytics.**

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - the recurring donations stats may take up to 24 hours to register since we do not check the USD value in realtime

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

Regarding the Total recurring donation taking up to 24hrs before reflecting, noted!
On Production, Solana works as expected,

The Total Donations in USD does not double.





![image](https://github.com/user-attachments/assets/6f19b5d8-9e31-4c9e-8e69-492b517f9fc8)
